title: CommandLine
description: "CommandLine blog"
author:
  name: "Sala"
  email: "andras.salamon@melda.info"
  url: "https://commandline.blog.hu"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 10
paginate_path: /page/:num/

disqus:
    shortname: commandline-blog

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
    - README.md

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Sala"
year : "2009-2020"
